#!/usr/bin/env bash

set -o errexit

for f in *.svg; do
  filename="${f%.svg}"
  inkscape "${f}" --export-area-page --batch-process --export-type=pdf --export-filename="${filename}.pdf"
done

readonly PAGES=("welcome.pdf" "history.pdf" "analogy-js.pdf" "analogy-ebpf.pdf" "probes.pdf" "benefits.pdf" "performance.pdf" "probes.pdf")
readonly OUT=master.pdf
pdfunite "${PAGES[@]/#/}" "${OUT}"
